### ISSUE TITLE
Código de status 429 - "Too Many Requests."

### ISSUE THREAD

**Issue by evelyn2png** [DevSamurai/food-gpt#3]
Em primeiro teste com a mensagem simples de "Olá" o bot funcionou normalmente. Mas após finalizado o código já não responde mais mensagens encaminhadas e apresenta mensagem de erro com o código de status 429 - "Too Many Requests.". Alguma orientação de como solucionar este problema? Se sim, seria através do código ou comente com a API da Openai?

**Comment by evelyn2png** [comment]
@felipefontoura consegue me dar um auxilio nisso?

**Comment by vitorsilveira93** [comment]
Boa noite, isso ocorre porque no plano FREE da OPENAI, você só pode fazer 3 requisições a cada minuto.
No Plano Pago, o número de requisições aumenta.
Aqui eu contornei isso, utilizando um DELAY de 30 segundos a cada requisição a API, dessa forma, não excedo o limite de requisições.

**Comment by deviego** [comment]
mas se você tem a sua conta criada antes de abril o credito free foi acabado, cria uma nova conta e coloca uma nova key
